title: Hello, world!
description: > # this means to ignore newlines until "baseurl:"
  nothing important.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Wang Yaxuan # add your name
author-img: yuanyuan.jpg # add your photo
about-author: I am a web developer focusing on front-end development. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: https://github.com/wangyaxuanFE/blog
# social-linkedin: # add your Linkedin handle
social-email: 18518389424@163.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
# plugins:
#   - jekyll-sitemap
#   - jekyll-paginate
#   - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
